"""Functional Chromium tests; no OBS/Windows hardware is claimed by these."""
import json
import os
import shutil
import subprocess
import threading
import time
from functools import partial
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import quote

import pytest
from playwright.sync_api import Error as PlaywrightError, sync_playwright

from bpm_bridge.detector import Estimate
from bpm_bridge.server import make_server
from bpm_bridge.state import BeatState


@pytest.fixture
def browser():
    with sync_playwright() as p:
        executable = os.environ.get("CHROMIUM_EXECUTABLE") or shutil.which("chromium")
        browser = p.chromium.launch(executable_path=executable, headless=True,
                                    args=["--no-sandbox", "--autoplay-policy=no-user-gesture-required"])
        yield browser
        browser.close()


def serve(state, banana=None):
    server = make_server(state, port=0, banana=banana)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    return server, f"http://127.0.0.1:{server.server_port}"


def test_animation_follows_tempo_phase_and_stops(browser):
    state = BeatState()
    state.publish(Estimate(90, 0.9, time.time(), 0.1))
    server, url = serve(state)
    page = browser.new_page()
    errors = []
    page.on("pageerror", lambda exc: errors.append(str(exc)))
    try:
        page.goto(url)
        page.wait_for_function("window.bananaBridge && bananaBridge.active()")
        for bpm in (90, 150):
            state.publish(Estimate(bpm, 0.9, time.time(), 0.1))
            page.wait_for_function(f"bananaBridge.state.bpm === {bpm}")
            page.wait_for_timeout(50)
            data = page.evaluate("""() => {
              const b = bananaBridge, a = b.targets[0].element;
              return {actual:a.currentTime, expected:
                (Date.now()/1000+b.clockOffset-b.state.beat_at)*(b.state.bpm/120)*1000};
            }""")
            assert abs(data["actual"]-data["expected"]) < 50
        state.unavailable("silent")
        page.wait_for_function("!bananaBridge.active()")
        page.wait_for_timeout(50)
        old = page.evaluate("bananaBridge.targets[0].element.currentTime")
        page.wait_for_timeout(150)
        assert page.evaluate("bananaBridge.targets[0].element.currentTime") == old
        # An interrupted bridge must also freeze the animation.
        assert not errors
    finally:
        page.close()
        server.shutdown()
        server.server_close()


def test_video_rate_and_bridge_disconnect(browser, tmp_path):
    if not shutil.which("ffmpeg"):
        pytest.skip("ffmpeg is needed to generate the functional video fixture")
    video = tmp_path / "clip.webm"
    subprocess.run(["ffmpeg", "-v", "error", "-f", "lavfi", "-i",
                    "testsrc2=size=128x128:rate=30:duration=2", "-c:v", "libvpx",
                    "-an", str(video)], check=True)
    state = BeatState()
    state.publish(Estimate(150, 0.9, time.time(), 0.1))
    server, url = serve(state, video)
    page = browser.new_page()
    try:
        page.goto(url)
        page.wait_for_function("window.bananaBridge && bananaBridge.targets.length && "
                               "bananaBridge.targets[0].element.readyState >= 2")
        page.wait_for_function("!bananaBridge.targets[0].element.paused")
        rate = page.evaluate("bananaBridge.targets[0].element.playbackRate")
        assert 1.18 <= rate <= 1.32
        state.publish(Estimate(90, 0.9, time.time(), 0.1))
        page.wait_for_function("bananaBridge.targets[0].element.playbackRate < 0.8")
        server.shutdown()
        server.server_close()
        page.wait_for_function("bananaBridge.targets[0].element.paused", timeout=5000)
    finally:
        page.close()
        server.shutdown()
        server.server_close()


@pytest.mark.parametrize("transport", ["file", "http"])
def test_selected_local_overlay_follows_tempo_without_extra_bounce(browser, tmp_path, transport):
    """Exercise the HTML generated by OBS against a real file and CORS service."""
    if not shutil.which("ffmpeg"):
        pytest.skip("ffmpeg is needed to generate the functional video fixture")
    video = tmp_path / "mi plátano & overlay.webm"
    subprocess.run(["ffmpeg", "-v", "error", "-f", "lavfi", "-i",
                    "testsrc2=size=128x128:rate=30:duration=2", "-c:v", "libvpx",
                    "-an", str(video)], check=True)
    state = BeatState()
    state.publish(Estimate(150, 0.9, time.time(), 0.1))
    # No --banana argument: the detector only supplies timing; OBS selects the file.
    server, url = serve(state)
    files = ThreadingHTTPServer(("127.0.0.1", 0),
                                partial(SimpleHTTPRequestHandler, directory=str(tmp_path)))
    threading.Thread(target=files.serve_forever, daemon=True).start()
    files_url = f"http://127.0.0.1:{files.server_port}"
    media_url = video.as_uri() if transport == "file" else files_url + "/" + quote(video.name)
    web = Path(__file__).resolve().parent.parent / "web"
    rendered = (web / "local-overlay.html").read_text(encoding="utf-8")
    replacements = {
        "__BRIDGE_SCRIPT__": (web / "bridge.js").read_text(encoding="utf-8").replace("</", r"<\/"),
        "__BRIDGE_URL_JSON__": json.dumps(url),
        "__MEDIA_URL_JSON__": json.dumps(media_url),
        "__BASE_BPM__": "120",
        "__PHASE_SECONDS__": "0",
    }
    for token, value in replacements.items():
        assert token in rendered, f"Missing local overlay template token: {token}"
        rendered = rendered.replace(token, value)
    overlay = tmp_path / "overlay.html"
    overlay.write_text(rendered, encoding="utf-8")
    page = browser.new_page()
    errors = []
    state_responses = []
    page.on("pageerror", lambda exc: errors.append(str(exc)))
    page.on("response", lambda response: state_responses.append(response)
            if response.url == url + "/state" else None)
    try:
        try:
            page.goto(overlay.as_uri() if transport == "file" else files_url + "/overlay.html")
        except PlaywrightError as exc:
            if transport == "file" and "ERR_BLOCKED_BY_ADMINISTRATOR" in str(exc):
                pytest.skip("Cloud Chromium enterprise policy blocks file://; run this case on a local browser")
            raise
        page.wait_for_function("window.bananaBridge && bananaBridge.active() && "
                               "document.getElementById('overlay-video').readyState >= 2")
        page.wait_for_function("!document.getElementById('overlay-video').paused")
        assert page.evaluate("document.getElementById('overlay-video').currentSrc") == media_url
        assert page.evaluate("bananaBridge.targets.length") == 1
        assert page.evaluate("bananaBridge.targets[0].kind") == "video"
        rate = page.evaluate("document.getElementById('overlay-video').playbackRate")
        assert 1.18 <= rate <= 1.32
        state.publish(Estimate(90, 0.9, time.time(), 0.1))
        page.wait_for_function("bananaBridge.state.bpm === 90 && "
                               "document.getElementById('overlay-video').playbackRate < 0.8")
        rate = page.evaluate("document.getElementById('overlay-video').playbackRate")
        assert 0.70 <= rate <= 0.80
        assert page.evaluate("document.getAnimations().length") == 0
        assert page.evaluate("getComputedStyle(document.getElementById('overlay-video')).animationName") == "none"
        assert state_responses
        assert state_responses[-1].header_value("access-control-allow-origin") == "*"
        assert state_responses[-1].request.header_value("origin") == ("null" if transport == "file" else files_url)
        state.unavailable("silent")
        page.wait_for_function("document.getElementById('overlay-video').paused")
        assert not errors
    finally:
        page.close()
        server.shutdown()
        server.server_close()
        files.shutdown()
        files.server_close()
